# Generated by Django 4.2.5 on 2023-09-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreP_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_store', to='StoreP_app.store_timezone'),
        ),
        migrations.AlterField(
            model_name='store_business_hour',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_hour', to='StoreP_app.store_timezone'),
        ),
        migrations.AlterField(
            model_name='store_status',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_store', to='StoreP_app.store_timezone'),
        ),
    ]
