# Generated by Django 4.2.5 on 2023-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreP_app', '0002_alter_report_store_alter_store_business_hour_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
