# Generated by Django 4.2.5 on 2023-09-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreP_app', '0003_alter_report_report_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_timezone',
            old_name='timezone',
            new_name='timezone_str',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store_business_hour',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store_status',
            name='store',
        ),
        migrations.AddField(
            model_name='report',
            name='restro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='StoreP_app.store_timezone'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=None),
        ),
        migrations.AddField(
            model_name='store_business_hour',
            name='restro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timmings', to='StoreP_app.store_timezone'),
        ),
        migrations.AddField(
            model_name='store_status',
            name='restro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='restro_status', to='StoreP_app.store_timezone'),
        ),
        migrations.AlterField(
            model_name='store_status',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactiveactive'), (1, 'Active')], default=None),
        ),
    ]
